collections:
  authors:
    output: true
  posts:
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      navigationItem: "Blog"
  - scope:
      path: ""
    values:
      layout: "default"